name: env
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scikit-learn
  - scikit-learn-intelex  # CPU acceleration for scikit-learn, see https://intel.github.io/scikit-learn-intelex/
  - pandas  # for datasource.py
  - black
  - pytest

